services:
  caddy:
    image: caddy:latest
    container_name: caddy-server
    hostname: caddy-server
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - "80:80"    # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # - ./data/caddy/sites:/usr/share/caddy/sites
      # - ./data/caddy/data:/data
      # - ./data/caddy/config:/config
    environment:
      - TZ=EST
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
     - nostr-daemon

#   minio:
#     container_name: minio
#     hostname: minio
#     image: minio/minio
#     restart: unless-stopped
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     env_file: "minio.env"
#     # environment:
#     #   MINIO_ACCESS_KEY: testaccesskey
#     #   MINIO_SECRET_KEY: testaccesssecretkey
#     volumes:
#       - ./data/minio:/data
#     command: "server --address \":9000\" --console-address \":9001\" /data"
#     networks:
#       - nostr-daemon

#   blossom:
#     container_name: blossom
#     hostname: blossom
#     image: ghcr.io/hzrd149/blossom-server:master
#     restart: unless-stopped
#     ports:
#       - 1971:3000
#     # enable debug logging
#     # environment:
#     #   Custom config path
#     #   BLOSSOM_CONFIG: "data/config.yml"
#     #   DEBUG: "*"
#     volumes:
#       # mount data volume
#       - ./data/blossom/data:/app/data
#       # mount config file
#       - ./blossom-config.yml:/app/config.yml
#       # mount custom www dir
#       # - ./data/public:/app/public
#       - ./data/blossom/blobs:/app/blobs
#     depends_on:
#       - minio
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     networks:
#       - nostr-daemon
  
#   db:
#     image: paradedb/paradedb:latest
#     container_name: ditto-postgres
#     hostname: ditto-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres 
#       POSTGRES_DB: ditto
#     ports:
#       - 127.0.0.1:5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - nostr-daemon

#   ditto:
#     image: ditto
#     container_name: ditto
#     hostname: ditto
#     restart: always
#     environment:
#       # Use https://nostrtool.com/ to generate a new one
#       DITTO_NSEC: "nsec1ssllvcypa7v3438m5fc7l7ncl6yxyfte0hpuhefljhg9skd6aams72tcyc"
#       # psql postgres://postgres:postgres@127.0.0.1:5432/ditto
#       DATABASE_URL: "postgres://postgres:postgres@ditto-postgres:5432/ditto"
#       LOCAL_DOMAIN: "https://social.mememaps.net"
#       PORT: "4036"
#     ports:
#       - 4036:4036
#     networks:
#       - nostr-daemon

# volumes:
#   postgres_data:

networks:
  nostr-daemon:
    external: true

